create table if not exists ad_items (
  id bigint generated by default as identity primary key,
  label text not null default '広告',
  title text not null,
  desc text,
  url text,
  color text default '#1a3a5c',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

alter table ad_items enable row level security;

create policy "Public read ad_items"
on ad_items for select using (true);

create policy "Service role all ad_items"
on ad_items for all using (true);

insert into ad_items (label, title, desc, url, color, active, sort_order) values
('広告', 'リフォームのご相談', '外壁・内装・水回りの工事は信頼の提携業者へ', 'https://www.gintetsu-fudosan.com', '#1a3a5c', true, 1),
('提携', '住宅ローン相談', 'ご成約者様に提携金融機関をご紹介します', 'https://www.gintetsu-fudosan.com', '#2d6a4f', true, 2),
('PR', '司法書士・税理士紹介', '不動産取得・相続のプロフェッショナルへ', 'https://www.gintetsu-fudosan.com', '#7b4f12', true, 3);
