-- ticker_items テーブル作成
create table if not exists ticker_items (
  id bigint generated by default as identity primary key,
  label text not null default 'PR',
  text text not null,
  url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

-- RLS有効化
alter table ticker_items enable row level security;

-- 誰でも読める（公開表示用）
create policy "Public read ticker_items"
on ticker_items for select
using (true);

-- サービスロールのみ書き込み可能
create policy "Service role insert ticker_items"
on ticker_items for insert
with check (true);

create policy "Service role update ticker_items"
on ticker_items for update
using (true);

create policy "Service role delete ticker_items"
on ticker_items for delete
using (true);

-- サンプルデータ
insert into ticker_items (label, text, url, active, sort_order) values
('PR', 'GINTETSUのAIコンシェルジュが不動産のお悩みを24時間サポート', 'https://www.gintetsu-fudosan.com', true, 1),
('提携', '住宅ローンのご相談｜ご成約者様に提携金融機関をご紹介', 'https://www.gintetsu-fudosan.com', true, 2),
('PR', 'リフォーム・外構工事のご相談｜信頼の提携業者をご紹介します', 'https://www.gintetsu-fudosan.com', true, 3);
